#
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Support for Python is experimental, and requires building SNAPSHOT image of Apache Spark,
# with `imagePullPolicy` set to Always

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: teehr-query
  namespace: teehr-spark-default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 935462133478.dkr.ecr.us-east-2.amazonaws.com/teehr-spark/spark-workflows:v20240502
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/query.py
  sparkVersion: "3.1.3"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 6
    coreLimit: "6000m"
    memory: "6000m"
    labels:
      version: 3.1.3
    serviceAccount: spark-operator
  executor:
    cores: 6
    instances: 1
    memory: "12000m"
    labels:
      version: 3.1.3