# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: ${var.hostname}-cert
# spec:
#   commonName: ${var.hostname}
#   dnsNames:
#   - ${var.hostname}
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   secretName: ${var.hostname}-tls

# ---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${var.hostname}-minio-cert
spec:
  commonName: minio.${var.hostname}
  dnsNames:
  - minio.${var.hostname}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: minio.${var.hostname}-tls