apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: teehr-spark-cluster
  region: us-east-2
  version: "1.27"

nodeGroups:
  - name: core-ng
    instanceType: r5.4xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
  - name: worker-ng
    instanceType: r5.4xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    labels:
      dedicated: worker
    taints:
      dedicated: "worker:NoSchedule"
    propagateASGTags: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
  - name: worker-ng-cpu
    instanceType: c7a.4xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 8
    labels:
      dedicated: worker-cpu
    taints:
      dedicated: "worker:NoSchedule"
    propagateASGTags: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true

iam:
  withOIDC: true
  serviceAccounts:
  # - metadata:
  #     name: ecr-poweruser
  #     # set namespace to your developer namespace
  #     namespace: teehr-spark-default
  #   attachPolicyARNs:
  #   - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser"
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  # - metadata:
  #     name: cluster-autoscaler
  #     namespace: teehr-spark-default
  #     labels: {aws-usage: "cluster-ops"}
  #   wellKnownPolicies:
  #     autoScaler: true
  #   roleName: eksctl-cluster-autoscaler-role
  #   roleOnly: true

addons:
- name: aws-ebs-csi-driver
  wellKnownPolicies:
    ebsCSIController: true